print("Hello Joël")
print("Joel écrit qq chose") # Houlala erreur print("Nouveau code super pratique") 
print("Je continue")
print("Hello world")
print("This is me")
print("Fun for everyone. Corrected")
